In [24]:
from ML_prepare import *
from Kfold_CV import *

In [25]:
df_cohorts_2 = df[df['Cohort'] == 'D1_2']
df_cohorts_2['Individual'].unique()

array([ 9, 10, 11, 12, 13, 14])

In [26]:
df_cohorts_1 = df[df['Cohort'] == 'D1_1']
df_cohorts_1['Individual'].unique()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
df_cohorts_2.iloc[:, 4:5]

HR_Max
96  -0.528976
97   1.242915
98  -1.009076
99  -0.828351
100 -0.048090
..        ...
163  0.351076
164 -1.172515
165 -1.291165
166 -1.020863
167  1.985460

[72 rows x 1 columns]

In [28]:
df_cohorts_2['Frustrated']

96     2
97     5
98     0
99     1
100    6
      ..
163    8
164    0
165    1
166    4
167    0
Name: Frustrated, Length: 72, dtype: int64

In [29]:
df_cohorts_2['Frustrated'].to_numpy()

array([2, 5, 0, 1, 6, 1, 4, 8, 2, 0, 2, 0, 0, 1, 0, 0, 2, 1, 0, 5, 0, 0,
       1, 0, 0, 3, 1, 1, 2, 1, 1, 3, 0, 2, 4, 0, 1, 4, 0, 1, 5, 1, 1, 8,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 3, 2, 1, 1, 1, 1, 0, 4, 0, 1, 6, 0,
       4, 8, 0, 1, 4, 0])

In [78]:
cohort_1_log = log_model_f.score(df_cohorts_1.iloc[:, 4:5], df_cohorts_1['Frustrated'])
cohort_2_log = log_model_f.score(df_cohorts_2.iloc[:, 4:5], df_cohorts_2['Frustrated'])
cohort_1_baseline = base_model_f.score(df_cohorts_1.iloc[:, 4:5], df_cohorts_1['Frustrated'])
cohort_2_baseline = base_model_f.score(df_cohorts_2.iloc[:, 4:5], df_cohorts_2['Frustrated'])
cohort_1_decision = dt_model_f.score(df_cohorts_1.iloc[:, 4:5], df_cohorts_1['Frustrated'])
cohort_2_decision = dt_model_f.score(df_cohorts_2.iloc[:, 4:5], df_cohorts_2['Frustrated'])

In [31]:
display(cohort1, cohort2)

0.19791666666666666

0.3333333333333333

In [79]:
pred_cohort_1_log = log_model_f.predict(df_cohorts_1.iloc[:, 4:5])
pred_cohort_2_log = log_model_f.predict(df_cohorts_2.iloc[:, 4:5])
pred_cohort_1_baseline = base_model_f.predict(df_cohorts_1.iloc[:, 4:5])
pred_cohort_2_baseline = base_model_f.predict(df_cohorts_2.iloc[:, 4:5])
pred_cohort_1_decision = dt_model_f.predict(df_cohorts_1.iloc[:, 4:5])
pred_cohort_2_decision = dt_model_f.predict(df_cohorts_2.iloc[:, 4:5])



pred_cohort = log_model_f.predict(df.iloc[:, 4:5])

In [33]:
contingency_table = pd.crosstab(df['Cohort'], df['Frustrated'])
contingency_table


Frustrated   0   1   2   3   4   5  6  7  8
Cohort                                     
D1_1         8  18  24  13  17  11  3  2  0
D1_2        21  27   7   3   6   3  2  0  3

In [40]:
print(np.mean(df_cohorts_1['Frustrated']), np.mean(df_cohorts_2['Frustrated']))
print(cohort1, cohort2)


2.7083333333333335 1.7361111111111112
0.19791666666666666 0.3333333333333333


In [43]:
len(df_cohorts_1['Frustrated']), len(df_cohorts_2['Frustrated'])

(96, 72)

In [57]:
# Specify the number of observations to remove
x = 24

# Randomly remove x observations from the dataset
df_removed = df_cohorts_1.sample(n=x, random_state=42)

# Create a new dataset without the removed observations
df_updated = df_cohorts_1.drop(df_removed.index)

# Print the updated dataset
df_cohorts_1_r = df_updated

In [63]:
import numpy as np

# Specify the number of observations to remove
x = 24

# Randomly remove x observations from the array
pred_cohort_1_r = np.random.choice(pred_cohort_1, size=len(pred_cohort_1)-x, replace=False)

# Print the updated array
len(pred_cohort_1_r)

72

In [64]:
from scipy.stats import ttest_rel

# Perform paired t-test
t_statistic, p_value = ttest_rel(pred_cohort_1_r, pred_cohort_2)

# Print the results
print("Paired t-test results:")
print("t-statistic:", t_statistic)
print("p-value:", p_value)



Paired t-test results:
t-statistic: 1.3492638068638843
p-value: 0.18153935880305644


In [34]:
predictions = pd.DataFrame({'Predicted': pred_cohort, 'Actual': df['Frustrated']})
table1 = pd.crosstab(predictions['Predicted'], df['Cohort'])

table2 = pd.crosstab(predictions['Predicted'], predictions['Actual'])

table3 = pd.crosstab(predictions['Predicted'], [predictions['Actual'],df['Cohort']])
from sympy import *
table3

Actual       0         1         2         3         4         5         6  \
Cohort    D1_1 D1_2 D1_1 D1_2 D1_1 D1_2 D1_1 D1_2 D1_1 D1_2 D1_1 D1_2 D1_1   
Predicted                                                                    
0            1    5    1    7    3    0    0    0    2    1    1    0    0   
1            7   16   17   19   20    7   12    3   14    5   10    3    3   
2            0    0    0    1    0    0    0    0    1    0    0    0    0   
3            0    0    0    0    1    0    1    0    0    0    0    0    0   

Actual            7    8  
Cohort    D1_2 D1_1 D1_2  
Predicted                 
0            1    1    0  
1            1    1    3  
2            0    0    0  
3            0    0    0

In [77]:
from sklearn.metrics import classification_report
print(classification_report(df_cohorts_1['Frustrated'], pred_cohort_1_log, zero_division=0), classification_report(df_cohorts_2['Frustrated'], pred_cohort_2_log, zero_division=0))

              precision    recall  f1-score   support

           0       0.11      0.12      0.12         8
           1       0.20      0.94      0.33        18
           2       0.00      0.00      0.00        24
           3       0.50      0.08      0.13        13
           4       0.00      0.00      0.00        17
           5       0.00      0.00      0.00        11
           6       0.00      0.00      0.00         3
           7       0.00      0.00      0.00         2

    accuracy                           0.20        96
   macro avg       0.10      0.14      0.07        96
weighted avg       0.11      0.20      0.09        96
               precision    recall  f1-score   support

           0       0.36      0.24      0.29        21
           1       0.33      0.70      0.45        27
           2       0.00      0.00      0.00         7
           3       0.00      0.00      0.00         3
           4       0.00      0.00      0.00         6
           5       0.00 

In [80]:
print(classification_report(df_cohorts_1['Frustrated'], pred_cohort_1_baseline, zero_division=0), classification_report(df_cohorts_2['Frustrated'], pred_cohort_2_baseline, zero_division=0))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         8
           1       0.19      1.00      0.32        18
           2       0.00      0.00      0.00        24
           3       0.00      0.00      0.00        13
           4       0.00      0.00      0.00        17
           5       0.00      0.00      0.00        11
           6       0.00      0.00      0.00         3
           7       0.00      0.00      0.00         2

    accuracy                           0.19        96
   macro avg       0.02      0.12      0.04        96
weighted avg       0.04      0.19      0.06        96
               precision    recall  f1-score   support

           0       0.00      0.00      0.00        21
           1       0.38      1.00      0.55        27
           2       0.00      0.00      0.00         7
           3       0.00      0.00      0.00         3
           4       0.00      0.00      0.00         6
           5       0.00 

In [81]:
print(classification_report(df_cohorts_1['Frustrated'], pred_cohort_1_decision, zero_division=0), classification_report(df_cohorts_2['Frustrated'], pred_cohort_2_decision, zero_division=0))

              precision    recall  f1-score   support

           0       0.46      0.75      0.57         8
           1       0.74      0.78      0.76        18
           2       0.62      0.83      0.71        24
           3       0.58      0.54      0.56        13
           4       0.73      0.47      0.57        17
           5       0.83      0.45      0.59        11
           6       0.67      0.67      0.67         3
           7       0.00      0.00      0.00         2

    accuracy                           0.65        96
   macro avg       0.58      0.56      0.55        96
weighted avg       0.66      0.65      0.63        96
               precision    recall  f1-score   support

           0       0.85      0.52      0.65        21
           1       0.81      0.78      0.79        27
           2       0.29      0.71      0.42         7
           3       0.43      1.00      0.60         3
           4       0.50      0.33      0.40         6
           5       1.00 